export const NEWS_GETTING = "NEWS_GETTING";
export const NEWS_GET_SUCCESS = "NEWS_GET_SUCCESS";
export const NEWS_GET_FAIL = "NEWS_GET_FAIL";

export const UPDATE_KEYWORD = "UPDATE_KEYWORD";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const UPDATE_SOURCE = "UPDATE_SOURCE";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const SOURCE_GETTING = "SOURCE_GETTING";
export const SOURCE_GET_SUCCESS = "SOURCE_GET_SUCCESS";
export const SOURCE_GET_FAIL = "SOURCE_GET_FAIL";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const DEL_FAVORITE = "DEL_FAVORITE";
